### ISSUE TITLE
Not all the conditions in NumaflowControllerRollout status are true

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaplane#511]
**Describe the bug**

Is following expected?

When creating a `NumaflowControllerRollout` as below, one of the conditions is `false`.

```yaml
apiVersion: numaplane.numaproj.io/v1alpha1
kind: NumaflowControllerRollout
metadata:
  name: numaflow-controller
spec:
  controller:
    #instanceID: "0" # uncomment for Progressive rollout to set Numaflow Controller instance
    version: "1.4.2"
```

Status
```yaml
status:
  conditions:
  - lastTransitionTime: "2025-01-20T07:28:05Z"
    message: Successful
    observedGeneration: 1
    reason: Successful
    status: "True"
    type: ChildResourceDeployed
  - lastTransitionTime: "2025-01-20T07:28:09Z"
    message: Successful
    observedGeneration: 1
    reason: Successful
    status: "True"
    type: ChildResourcesHealthy
  - lastTransitionTime: "2025-01-20T07:28:05Z"
    message: no need for pause
    observedGeneration: 1
    reason: NoPause
    status: "False"
    type: PausingPipelines
```

Feel free to close it if it's not a bug.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.
