### ISSUE TITLE
e2e ppnd test - Pipeline is getting stuck during deletion (on the CI)

### ISSUE THREAD

**Issue by dpadhiar** [numaproj/numaplane#559]
**Describe the bug**

In the PPND e2e test suite, we have a test case that tries to successfully update a PipelineRollout, ISBServiceRollout and NumaflowControllerRollout if there is a dependent failed Pipeline. Currently the PipelineRollout and NumaflowControllerRollout cases are passing without failure but the ISBServiceRollout test seems to be consistently failing on the CI only.

The failure is consistently occurring after the main feature has been tested successfully and we are cleaning up the failed PipelineRollout. The PipelineRollout is waiting to be verified as deleted and never happens causing a timeout and test suite failure. 

With investigation into the resources artifacts, we see that the child Pipeline has a deletionTimestamp as well as the pipeline-controller finalizer still. This explains why the Pipeline is essentially "hanging" during deletion and informs us the Numaflow controller is not successfully removing the finalizer.

Need to investigate further to see why this only occurs on the CI and not locally. 

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: "2025-02-11T17:09:20Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2025-02-11T17:10:28Z"
  finalizers:
  - pipeline-controller
```

**To Reproduce**

1. Uncomment test and let CI run.

**Expected behavior**

Test to pass successfully on the CI and locally.

**Additional context**

Locally the test is passing which informs us that the issue may be CI related.
A change was made recently to Numaplane which prevents a Rollout from being deleted before its child resource. This change should not have impacted this case or issue but it may have.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.
