### ISSUE TITLE
Flakey test - Progressive Functional Pipeline - isbsvc upgrade - Daemon pod can't start due to insufficient memory

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#664]
**Test**: Progressive Functional Pipeline

**What happened?:**
When isbsvc was trying to go through Progressive Rollout, the pipeline also went through Progressive Rollout. However, it failed due to a Daemon Pod not being able to start:
This was the Status for the Daemon Pod:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-03-21T04:36:16Z"
    message: '0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes
      are available: 1 No preemption victims found for incoming pod.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

[Archive 5.zip](https://github.com/user-attachments/files/19382302/Archive.5.zip)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.
