### ISSUE TITLE
Prevent more than 1 NumaflowControllerRollout on a namespace

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#7]
The easiest way to take care of this is to only allow one name for the `NumaflowControllerRollout`, e.g. "numaflow-controller" (in which case our [sample](https://github.com/numaproj-labs/numaplane/blob/rolloutControllers/config/samples/numaplane.numaproj.io_v1alpha1_numaflowcontrollerrollout.yaml#L4) is wrong and should be changed).

Addresses [this](https://github.com/numaproj-labs/numaplane/blob/96010907b30ebe8e4a0072abc8a5140bee55683c/internal/controller/numaflowcontrollerrollout_controller.go#L123) todo.

**Comment by chandankumar4** [comment]
Should it be good to add validation check in CRD as well, like below
```yaml
          metadata:
            type: object
            properties:
              name:
                type: string
                pattern: ^numaflow-controller$
```
