### ISSUE TITLE
e2e testing for AnalysisRuns

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#750]
I'm thinking we can probably have a new test for this. Only needs to run for "progressive" strategy.

Ideally, we should test this for both PipelineRollout and MonoVertexRollout. Perhaps the test can initially do a Progressive upgrade with resource health check passing and AnalysisTemplate failing, then use a different AnalysisTemplate which passes and do another Progressive upgrade. This should pass.

Here is an example AnalysisTemplate we've used with a trivial prometheus query:
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: mvtx-template
  namespace: example-namespace
spec:
  args:
    - name: upgrading-monovertex-name
    - name: promoted-monovertex-name
    - name: monovertex-namespace
    - name: prometheus-port
      value: '9090'
  metrics:
  - name: mvtx-example
    # interval: 1m
    failureLimit: 10
    provider:
      prometheus:
        address: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:{{args.prometheus-port}}"
        query: |
          increase(numaflow_monovtx_ack_total{namespace="{{args.monovertex-namespace}}", mvtx_name="{{args.upgrading-monovertex-name}}", mvtx_replica="0"}[1m])
    successCondition: len(result) == 0 # success
    #successCondition: result[0] >= 0 # failure
```

See the `successCondition` above for success and the one for failure. 

Even better, consider using 2 AnalysisTemplates at the same time: in the failure case, one should pass but the other one should fail. In the success case, both of them need to pass. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
